### ISSUE TITLE
View local HTML?

### ISSUE THREAD

**Issue by anthonysmaldone** [TLabAltoh/TLabWebViewVR#26]
I need to be able to view an HTML file that is locally stored, however I get an `ERR_ACCESS_DENIED` error. Is there anything that can be done to view my file in the webview browser? Currently I am setting the URL with the `file:\\` prefix. After granting read permissions, I still seem to be having the error. Thanks.

**Comment by TLabAltoh** [comment]
In my Java plugin, it denied file access by file url scheme and maybe that's cause problem. now repository are updated with fixed version (only tested android smartphone). Also, after Android 11, it needs to add follow permission to allow access to external storage (like download, image, etc...).

```.xml
<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE" />
```

and need to call this function at runtime.

```.cs
UnityEngine.Android.Permission.RequestUserPermission("android.permission.MANAGE_EXTERNAL_STORAGE");
```

The above permission is required to access external storage, but I recommend using Streaming Asset to load HTML content. 

This is an example of how to extract the archived file (e.g. zip) into the application folder. This process is necessary because webview cannot access the ```jar:file://``` url scheme (this is the path for the archived data in the apk file, path for streaming asset is uses this url scheme).

<details><summary>Sample Code</summary>

```.cs

[SerializeField] private TLabWebView m_webview;

// Load local html file from extracted zip file placed in application folder 
public void OpenLocalHTML(string filePath)
{
    var url = "file://" + Application.persistentDataPath + "/local-html";

    url += ("/" + filePath);

    Debug.Log(THIS_NAME + $"url: {url}");

    m_webview.LoadUrl(url);
}

// Copy streaming assets/local-html.zip to application folder root/local-html/
private void Start()
{
    var subPath = "/local-html";

    var srcZip = Application.streamingAssetsPath + subPath + ".zip";

#if UNITY_EDITOR
    var dstPath = Application.dataPath;
#else
    var dstPath = Application.persistentDataPath;
#endif
    var dstZip = dstPath + $"{subPath}/{subPath}.zip";

    var outputDir = dstPath + "/" + subPath;
    if (Directory.Exists(outputDir))
    {
        Directory.Delete(outputDir, true);
    }

    Directory.CreateDirectory(outputDir);

    var request = new WWW(srcZip);
    while (!request.isDone) { }

    if (!File.Exists(dstZip))
    {
        File.WriteAllBytes(dstZip, request.bytes);
    }
    else
    {
        File.Delete(dstZip);
        File.WriteAllBytes(dstZip, request.bytes);
    }

    ZipFile.ExtractToDirectory(dstZip, outputDir);

    Debug.Log(THIS_NAME + $"done !");
}
```

</details>

I'm not confirming the behaviour for the file url scheme enough yet, so there may be another update.

**Comment by anthonysmaldone** [comment]
Thanks, worked great!
