### ISSUE TITLE
PageDown/PageUp? [request]

### ISSUE THREAD

**Issue by C0170N** [TLabAltoh/TLabWebViewVR#27]
I see there is already a method for GetScroll and SetScroll in the scripting API, but would it be possible to add the ability to do pageUp and pageDown? I believe that is a normal method for Android webview but I don't currently see it in the documentation for the scripting API. Thank you

**Comment by TLabAltoh** [comment]
I have updated the repository by adding ```Page Down/Up```, but now there is a limitation.

The return value of webview's ```Page Down/Up``` is ignored because the webview thread is separate from the unity thread, so it's impossible to get the webview function result by synchronising.

[Scripting API (Page Down/Up)](https://app.gitbook.com/o/BEOtLe2RJogUYj62ljWp/s/mRKt4CGSxyWYs97naGI6/documentation-en/scripting-api#pageup)

**Comment by C0170N** [comment]
Thank you, this was a great help and it worked well.
