### ISSUE TITLE
How to trigger the keyboard and seach bar ui :? 

### ISSUE THREAD

**Issue by TREEANA** [TLabAltoh/TLabWebViewVR#29]
Hi, I would like to change the interaction controller to eye gaze.

I've changed the web view, but I couldn't change the keyboard and search bar.

I have no idea how the scripts triggers the keyboard and search bar.

Are there any event controller scripts similar to a WebView input listener?

**Comment by TLabAltoh** [comment]
Currently you can only interact with WebView? both WebView and Keyboard Interact are based on uGUI's pointer event. and if it is difficult to implement a keyboard system, you can use Oculus' system keyboard. also search bar can replace uGUI's input field (uGUI's input field can be interacted with Oculus' system keyboard).


[keyborad overlay](https://developer.oculus.com/documentation/unity/unity-keyboard-overlay/)

**Comment by TREEANA** [comment]
yes I can only interact with webview. 

![image](https://github.com/TLabAltoh/TLabWebViewVR/assets/76998594/22502b68-c903-4c10-8f34-0825e5208180)"

I changed the TLabWebViewinputlister.cs which use the left and right gaze instead of using PointerEventData. 

However I could not found the scripts for keyboard. 

And If I change the  the   Oculus' system keyboard, parameter which used  simplekeyborad would be a problem? 
like below

![image](https://github.com/TLabAltoh/TLabWebViewVR/assets/76998594/6119c78f-d75e-45ea-8b34-22c8ce2b0ea3)

**Comment by TLabAltoh** [comment]
Can you interact with other UI (like a button) using the eye pointer? 

Simple Keyboard can be separated (removed) from WebView, so it is possible to avoid behavior conflict between Simple Keyboard and System Keyboard. 

If it is possible to use eye pointer on system keyboard, it is recommended to use system keyboard instead of Simple Keyboard. If not, and eye pointer cannot interact with uGUI, recommend to use simple keyborad and your own input module (is that what you are doing now?). 

simple keyborad uses uGUI's button to fire key down event, so you need to create and handle pointer event to interact with uGUI's button. maybe [this code](https://github.com/FusedVR/Oculus-Quest-VRTK/blob/master/Assets%2FOculus%2FVR%2FScripts%2FUtil%2FOVRInputModule.cs) can be good example to create custom input module with small code (normaly, creating custom input module needs hard work).

**Comment by TREEANA** [comment]
ty 

I tried to make the webview scroll using eye gaze
For this can make an api called ScrollTo for us to use?
public void SimulateScroll(int deltaX, int deltaY)
{
    if (!m_webViewEnable || m_NativePlugin == null)
    {
        return;
    }

#if UNITY_ANDROID && !UNITY_EDITOR || DEBUG
    m_NativePlugin.Call("scrollTo", deltaX, deltaY);
#endif
}
 
Something like this
or Scrollby

**Comment by TLabAltoh** [comment]
added latest update, [scrollTo](https://app.gitbook.com/o/BEOtLe2RJogUYj62ljWp/s/mRKt4CGSxyWYs97naGI6/documentation-en/scripting-api#scrollto) and [scrollBy](https://app.gitbook.com/o/BEOtLe2RJogUYj62ljWp/s/mRKt4CGSxyWYs97naGI6/documentation-en/scripting-api#scrollby) in the latest update.
