### ISSUE TITLE
[Package Manager Window] Error adding package: 

### ISSUE THREAD

**Issue by JGameMaker92** [TLabAltoh/TLabWebViewVR#30]
Unable to add the package to Unity using the Package Manager and the git url

**Comment by TLabAltoh** [comment]
Please let me know which package you cannot add. TLabWebview and TLabVKeyborad are managed by submodule and it is automatically added when you run ```git submodule update --init```, so you only need to add Meta XR SDK and XR Interaction Toolkit.

**Comment by TLabAltoh** [comment]
Currently I don't manage as package for folder TLabWebViewVR because it's just implementation example, and it's not using additional script. if you migrate prefab in your project, please try to use this script to download prefab from remote to your specific directory.

<details><summary>download meta xr webview prefab</summary>

```bat
curl -O https://github.com/TLabAltoh/TLabWebViewVR/blob/master/Assets/TLab/TLabWebViewVR/MetaXR/TLabWebView_MetaXR.prefab
curl -O https://github.com/TLabAltoh/TLabWebViewVR/blob/master/Assets/TLab/TLabWebViewVR/MetaXR/TLabWebView_MetaXR.prefab.meta
```

</details>

<details><summary>download xr interaction toolkit webview prefab</summary>

```bat
curl -O https://github.com/TLabAltoh/TLabWebViewVR/blob/master/Assets/TLab/TLabWebViewVR/XRInteractionToolkit/TLabWebView_XRInteractionToolkit.prefa://github.com/TLabAltoh/TLabWebViewVR/blob/master/Assets/TLab/TLabWebViewVR/XRInteractionToolkit/TLabWebView_XRInteractionToolkit.prefab
curl -O https://github.com/TLabAltoh/TLabWebViewVR/blob/master/Assets/TLab/TLabWebViewVR/XRInteractionToolkit/TLabWebView_XRInteractionToolkit.prefa://github.com/TLabAltoh/TLabWebViewVR/blob/master/Assets/TLab/TLabWebViewVR/XRInteractionToolkit/TLabWebView_XRInteractionToolkit.prefab.meta
```

</details>

**Comment by JGameMaker92** [comment]
Why are you doing things the difficult way? Everyone uses the Package Manager, it's so much easier. I'm still trying to figure out how to get these files in my project days later. I have the com.tlab.webview folder in my packages folder of my project but it is still not letting me import it

**Comment by TLabAltoh** [comment]
I have updated the repository to be able to import each module using the package manager. Please import using the url below. Only XR Interaction Toolkit has not been tested, so may be updated later. 

|  module / sample  |  url  |
| --- | --- |
| TLabVKeyborad | https://github.com/TLabAltoh/TLabVKeyborad.git |
| TLabWebView | https://github.com/TLabAltoh/TLabWebView.git |
| Meta XR Sample | https://github.com/TLabAltoh/TLabWebViewVR.git?path=Assets/TLab/TLabWebViewVR/MetaXR |
| XR Interaction Toolkit | https://github.com/TLabAltoh/TLabWebViewVR.git?path=Assets/TLab/TLabWebViewVR/XRInteractionToolkit |

It's true that my suggestion is not best practice. I will support the package manager not only for this repository, but for other sample repositories later on.

**Comment by JGameMaker92** [comment]
Nice work! I’ve finally got the files in my project. Couldn’t get the scene files to open though
![Image 5-23-24 at 2 31 AM](https://github.com/TLabAltoh/TLabWebViewVR/assets/46422203/da4c2b27-56fa-41b2-ae3f-96d1f89b95f8)

**Comment by TLabAltoh** [comment]
I forgot to add support for Unity scenes, so I have updated the repository so that sample scenes can now be edited by importing them as samples. Also, the git url for the unity package manager has changed, so please add "#upm" for the preview git url. I have fixed the previous comment and the table of module git urls.
