### ISSUE TITLE
Is it possible to have two Webviews and more in one scene?

### ISSUE THREAD

**Issue by aequivalent2** [TLabAltoh/TLabWebViewVR#5]

**Comment by TLabAltoh** [comment]
Thanks for the comment.
TLabWebView does not support multiple instances yet, but as soon as it does, I will include it in the next update (I don't think it'll take long. Just give me a minute).

**Comment by aequivalent2** [comment]
Okay thanks have a nice Day

**Comment by TLabAltoh** [comment]
# TLabWebViewVR now supports multiple instances
[Demonstration Video](https://youtube.com/shorts/qWg_kmSCfxM?feature=share)
## How to check how it works
I have prepared multiple WebView instances for the OculusIntegration sample scene. You can check the behavior with multiple instances by enabling the disabled WebView instances and building the scene.
## Currently not possible
- Play youtube on multiple webviews at the same time (While one is playing, videos playing in other WebView instances are paused).
## Note
- The system is still in the process of becoming operational. If you encounter any problems, please do not hesitate to let me know.

**Comment by aequivalent2** [comment]
Thank you i will test it out tomorrow :)

**Comment by aequivalent2** [comment]
Is it normal that the Racast Dummy is missing in the XR Toolkit?

**Comment by TLabAltoh** [comment]
Yes. The raycast dummy has been removed from the project as it is no longer needed due to changes in the system design.


 (Before the change, raycast dummy was necessary because physics.raycast() was used to determine the intersection of the WebView panel and rays. Now, the intersection is determined based on the positional relationship of the ray pointer to the panel. (You can check the implementation in the TLabWebViewXRInputListener.cs))

**Comment by aequivalent2** [comment]
Hello i tested it with the XR-Toolkit and i ran into one Problem. I attached the error code
![Screenshot 2023-10-08 133355](https://github.com/TLabAltoh/TLabWebViewVR/assets/119690710/ebfb63f9-be98-43d8-bfea-06f931a8de0c)

**Comment by TLabAltoh** [comment]
Thanks for reporting this.

The error may be that you are using an older version of the code in Assets/TLab/TLabWebView, replacing the Assets/TLab folder with the latest commit from that repository may fix the error.

(This repository is subject to frequent fatal changes, so code compatibility between versions is low).

If you have made changes to prefabs or other files inside Asset/TLab, please save them once to a folder other than Asset/TLab so that you can continue working on them after the update.

I have not yet checked if the bug can be reproduced, so I'll check on my end.

**Comment by aequivalent2** [comment]
Hello, sorry to bother you but i tried it and the both webviews are displaying the same image in the XR-Interaction Toolkit

**Comment by TLabAltoh** [comment]
I'm sorry. There was a mistake in my earlier comment.

////////////////////////////////
replacing the Assets/TLab folder with the latest commit from ~~that~~ this repository may fix the error.
////////////////////////////////

Only this repository has multi-instance WebView support, so replace Asset/TLab with the latest commit from this repository.

**Comment by aequivalent2** [comment]
Thanks now it works perfectly fine. Thank you very much :)
